New Docs Site deployment structure info
RockefellerArchiveCenter/docs-guide pull request #20
Opened 2022-04-27 17:22 UTC by daremiyo

2022-04-27 17:36 UTC, helrond requested changes
Just one tweak to the language.

2022-04-27 17:36 UTC, helrond commented on using-github.md
> +6. Add a [GitHub Webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks) to the repository. Webhooks are added in the Settings page of a repository. The Webhook li
```suggestion
6. Add a [GitHub Webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks) to the repository. Webhooks are added in the Settings page of a repository. The Webhook listens for `push` events which push the updates to the development and production servers, and it should point to the AWS API Gateway endpoint for the `build_docs_site_api`. Contact the Head of Digital Strategies for the token and AWS Gateway endpoint URL you will need as part of the webhook configuration. For more information, see the [Documentation Site Info Sheet](https://docs.rockarch.org/systems-info-sheets/documentation-site-info-sheet/).
```

2022-04-27 18:10 UTC, HaSistrunk commented on add-content.md
> +4. Review the changes on the RAC development server at docs.dev.rockarch.org.
```suggestion
4. Review the changes on the [RAC development site](docs.dev.rockarch.org).
```

2022-04-27 18:13 UTC, HaSistrunk commented
One step I think we need to add is adding new documentation to the `repositories.yml` file in the `docs-build` repo as specified in the docs-build README: https://github.com/RockefellerArchiveCenter/docs-build#adding-or-removing-repositories

2022-04-27 19:00 UTC, daremiyo commented
> One step I think we need to add is to add new documentation to the `repositories.yml` file in the `docs-build` repo as specified in the docs-build README: https://github.com/RockefellerArchiveCenter/docs-build#adding-or-removing-repositories
 
Thanks for the catch!

2022-04-28 13:36 UTC, helrond approved these changes

2022-04-28 13:49 UTC, kemartin2015 approved these changes

2022-05-02 17:18 UTC, daremiyo commented
hi @HaSistrunk I put in a step for adding new documentation to the repositories.yml file under the Create a Repo section

2022-05-02 18:34 UTC, HaSistrunk approved these changes
Looks good!

2022-05-02 18:57 UTC, merged